# Generated by Django 5.2.3 on 2025-06-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_draft_advertisement_favourite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favourite',
        ),
        migrations.CreateModel(
            name='FavoriteAdvertisement',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='advertisements.advertisement')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('advertisements', models.ManyToManyField(related_name='favorited_by', to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
            bases=('advertisements.advertisement',),
        ),
    ]
